### ISSUE TITLE
Change learning goals to "will be able to..."

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/NSIDC-Data-Tutorials#3]
For example, change "After using this notebook you should be able to:" to "On completely this tutorial you will be able to..."

**Comment by betolink** [comment]
I just made some changes to the text and merged your PR. This should address most of the issues you opened regarding just text. I feel like when we are just modifying text and note code we should open a single issue and list the changes instead of opening an issue for each change. And with the jupyter format being a bit unreadable I installed https://app.reviewnb.com/, free for open source repos, it requires some permissions from your github account.

**Comment by asteiker** [comment]
With our notebook templating coming, and Luis's fix last year, I'm closing this out.
